dataset_id: your-prod-dataset-id
project_id: your-prod-gcp-project-id
schema:
  fields:
  - description: Unique identifier
    mode: REQUIRED
    name: id
    type: STRING
  - description: Record creation timestamp
    mode: NULLABLE
    name: created_at
    type: TIMESTAMP
table_id: your-prod-table-id
